apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: order
        image: order-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: ecommerce
        - name: DB_USER
          value: ecommerce_user
        - name: DB_PASS
          value: secret123
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5002"
spec:
  selector:
    app: orders
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
